In [1]:
import numpy as np
from scipy.optimize import curve_fit

def test_func(data):
    return data[0] + data[1] + data[2] + 40

xdata = np.linspace(1, 4, 50)
ydata = np.linspace(1, 4, 50) + 0.2 * np.random.randn(50)
zdata = np.linspace(1, 4, 50) + 0.2 * np.random.randn(50)

data = np.array([xdata, ydata, zdata])

def func_to_fit(data, a, b, c):
    return data[0] + data[1] + data[2] + a + b + c

curve_fit(func_to_fit, data, test_func(data))


/home/james/.cache/pypoetry/virtualenvs/formula-finder-VzUa6P_7-py3.8/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',


(array([ 59.333334 , -47.0000007,  27.6666667]),
 array([[inf, inf, inf],
        [inf, inf, inf],
        [inf, inf, inf]]))

In [2]:
from formula_finder.genetic_helpers import add_x_and_custom_variables_to_ending_indicies
from formula_finder.variables import get_ending_indicies, CUSTOM_VARIABLES_INDICIES, add_custom_variables, get_ending_indicies_that_are_not_leaf_nodes, replace_ending_index_with_random_node
import numpy as np
from formula_finder.binary_tree import (
    depth_of_tree,
    number_of_leaf_nodes_in_binary_tree,
)
add_custom_variables(["m1", "m2"])
chromosome = np.array([22, 14, 23, 14, 24, 20, 13, 23,  0, 23, 24, 24, 24, 22, 21])
# print(get_ending_indicies_that_are_not_leaf_nodes(chromosome))
# ending_indicies = get_ending_indicies(chromosome)
# print(ending_indicies)
# leaf_count = number_of_leaf_nodes_in_binary_tree(depth_of_tree(len(chromosome)))
# temp_chromosome = np.array(chromosome)
# for i in range(3):
#     print("leaf nodes", leaf_count)
#     print("ending non leaf nodes", get_ending_indicies_that_are_not_leaf_nodes(temp_chromosome))
#     print("ending nodes", get_ending_indicies(temp_chromosome))
#     print("CUSTOM_VARIABLES_INDICIES", CUSTOM_VARIABLES_INDICIES)
#     temp_chromosome = replace_ending_index_with_random_node(temp_chromosome)
#     print(temp_chromosome)
    
# print("==========================================================")
# print("to apply", [
#         x for x in CUSTOM_VARIABLES_INDICIES + [0] if x not in ending_indicies
#     ])

# print(len(chromosome), leaf_count, depth_of_tree(len(chromosome)), chromosome[-leaf_count:])
# print("test", replace_ending_index_with_random_node(chromosome))
chromosome2 = add_x_and_custom_variables_to_ending_indicies(chromosome)
# depth_of_tree(1)
ending_indicies2 = get_ending_indicies(chromosome2)
print("ending_indicies2", chromosome, chromosome2)
ending_indicies = get_ending_indicies(chromosome)
print(chromosome2[ending_indicies])
np.array([22, 14, 23, 14, 24, 20, 13, 23,  0, 23, 24, 24, 24, 22, 21]) - chromosome2

# CUSTOM_VARIABLES_INDICIES


variables_to_apply [23, 24, 0]

ending_indicies2 [ 8 14 23 14 24 20 13 23  0 23 24 24 24 22 21] [ 8 14 23 14 24 20 13 23  0 23 24 24 24 22 21]
[23  0 24 23]


array([14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])